{
  "formatVersion": "1.1",
  "component": {
    "url": "../../koalaplot/0.9.1/koalaplot-0.9.1.module",
    "group": "dev.zwander",
    "module": "koalaplot",
    "version": "0.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "koalaplot-core-wasm-js-0.9.0-dev.klib",
          "url": "koalaplot-wasm-js-0.9.1.klib",
          "size": 733794,
          "sha512": "59c04f1802763d2fab5185bb46a0484bff9be1be167f3364a4b558b7f01854bd682458f67765745dd29e38013b5ec29c0cdc8b158d7570e4edcc0d2ba043479d",
          "sha256": "334b10768ea15e253565ebab8c73a6cabdae0f09c3e7503438d56ab1ad8e09c1",
          "sha1": "fc0b4db7cf417b59c04ebd72c19430e912f7c0fe",
          "md5": "0d4727b36ec70bc568db9442f6c90d7c"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "koalaplot-core-wasm-js-0.9.0-dev.klib",
          "url": "koalaplot-wasm-js-0.9.1.klib",
          "size": 733794,
          "sha512": "59c04f1802763d2fab5185bb46a0484bff9be1be167f3364a4b558b7f01854bd682458f67765745dd29e38013b5ec29c0cdc8b158d7570e4edcc0d2ba043479d",
          "sha256": "334b10768ea15e253565ebab8c73a6cabdae0f09c3e7503438d56ab1ad8e09c1",
          "sha1": "fc0b4db7cf417b59c04ebd72c19430e912f7c0fe",
          "md5": "0d4727b36ec70bc568db9442f6c90d7c"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "koalaplot-core-wasm-js-0.9.0-dev-sources.jar",
          "url": "koalaplot-wasm-js-0.9.1-sources.jar",
          "size": 113560,
          "sha512": "b8d490e3692fb04620fad136b5f90606bffa6f3806c82cfdf8023f12d21a772b3026e0fed314c21890ee1d3fc09ab4e78994eed96c5f6330bf60ce6bed9ee8a1",
          "sha256": "c5f13282c1f1ed444afb92ad740d4c3f4a49a1f0161e3bfc43815c273271bc66",
          "sha1": "590a3699114a2740b070edb10f2d56bc38488555",
          "md5": "c90ad6192147965860a512768f9321f6"
        }
      ]
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "koalaplot-core-0.9.0-dev.kotlin_resources.zip",
          "url": "koalaplot-wasm-js-0.9.1-kotlin_resources.kotlin_resources.zip",
          "size": 360,
          "sha512": "540a2e7a9a0b84fa31483ddff5c65f0adb959a423d6f1661c8f5321cebb29757235406124f9a901142de045ac68ef1c991c5c57d7a40e3cf9ad6436c8021296a",
          "sha256": "baa5a97ecc8fa94d6f9c7a9684ff07d6c4ad4d4d5a259ffb81c4df1a6c1186fd",
          "sha1": "ccf77b00d4fef6c66a783c46093b1d3863703db0",
          "md5": "5bda121d2baa3bbc0596db4cd3fd11af"
        }
      ]
    }
  ]
}
