{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.zwander",
    "module": "koalaplot",
    "version": "0.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "koalaplot-core-metadata-0.9.0-dev.jar",
          "url": "koalaplot-0.9.1.jar",
          "size": 66282,
          "sha512": "b5a998aa82cea19b1d693112bbe4db26b4a88093011670034b68344ed664c7033cab646db604d546d6ab5fb2506c27da1af5754fd7a3d29230bde8bc1993f2f7",
          "sha256": "dd6b0549d4c889ae7bd6114772043b41cea698a7e124de989fec6c9b3da78eb3",
          "sha1": "b719a64be6e2c5be2d84cefdc0ac11194e0e9236",
          "md5": "12824e7123b6db0f970d7b2cd8b2ab02"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "koalaplot-core-kotlin-0.9.0-dev-sources.jar",
          "url": "koalaplot-0.9.1-sources.jar",
          "size": 112990,
          "sha512": "224a0a473344fcd649da6b986eb1fe5004e5cafecd98d1e652be882b3b24a633f8789e3b93ce5b103c22e41187482be98af72c34d87be23322fb7fdd5cc4ccd2",
          "sha256": "85f656d06218a0133cb1c76756d25c6f7a19b2a1fa4380ab423bfa40a615d829",
          "sha1": "e9275ef87ec6a78cfee7a4ec7991715876b41c66",
          "md5": "ba5656e36495438fc29cd6e1cdee9ba6"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../koalaplot-android/0.9.1/koalaplot-android-0.9.1.module",
        "group": "dev.zwander",
        "module": "koalaplot-android",
        "version": "0.9.1"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../koalaplot-android/0.9.1/koalaplot-android-0.9.1.module",
        "group": "dev.zwander",
        "module": "koalaplot-android",
        "version": "0.9.1"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../koalaplot-android/0.9.1/koalaplot-android-0.9.1.module",
        "group": "dev.zwander",
        "module": "koalaplot-android",
        "version": "0.9.1"
      }
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../koalaplot-desktop/0.9.1/koalaplot-desktop-0.9.1.module",
        "group": "dev.zwander",
        "module": "koalaplot-desktop",
        "version": "0.9.1"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../koalaplot-desktop/0.9.1/koalaplot-desktop-0.9.1.module",
        "group": "dev.zwander",
        "module": "koalaplot-desktop",
        "version": "0.9.1"
      }
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../koalaplot-desktop/0.9.1/koalaplot-desktop-0.9.1.module",
        "group": "dev.zwander",
        "module": "koalaplot-desktop",
        "version": "0.9.1"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koalaplot-iosarm64/0.9.1/koalaplot-iosarm64-0.9.1.module",
        "group": "dev.zwander",
        "module": "koalaplot-iosarm64",
        "version": "0.9.1"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koalaplot-iosarm64/0.9.1/koalaplot-iosarm64-0.9.1.module",
        "group": "dev.zwander",
        "module": "koalaplot-iosarm64",
        "version": "0.9.1"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koalaplot-iosarm64/0.9.1/koalaplot-iosarm64-0.9.1.module",
        "group": "dev.zwander",
        "module": "koalaplot-iosarm64",
        "version": "0.9.1"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koalaplot-iosarm64/0.9.1/koalaplot-iosarm64-0.9.1.module",
        "group": "dev.zwander",
        "module": "koalaplot-iosarm64",
        "version": "0.9.1"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koalaplot-iossimulatorarm64/0.9.1/koalaplot-iossimulatorarm64-0.9.1.module",
        "group": "dev.zwander",
        "module": "koalaplot-iossimulatorarm64",
        "version": "0.9.1"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koalaplot-iossimulatorarm64/0.9.1/koalaplot-iossimulatorarm64-0.9.1.module",
        "group": "dev.zwander",
        "module": "koalaplot-iossimulatorarm64",
        "version": "0.9.1"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koalaplot-iossimulatorarm64/0.9.1/koalaplot-iossimulatorarm64-0.9.1.module",
        "group": "dev.zwander",
        "module": "koalaplot-iossimulatorarm64",
        "version": "0.9.1"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koalaplot-iossimulatorarm64/0.9.1/koalaplot-iossimulatorarm64-0.9.1.module",
        "group": "dev.zwander",
        "module": "koalaplot-iossimulatorarm64",
        "version": "0.9.1"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koalaplot-iosx64/0.9.1/koalaplot-iosx64-0.9.1.module",
        "group": "dev.zwander",
        "module": "koalaplot-iosx64",
        "version": "0.9.1"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koalaplot-iosx64/0.9.1/koalaplot-iosx64-0.9.1.module",
        "group": "dev.zwander",
        "module": "koalaplot-iosx64",
        "version": "0.9.1"
      }
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koalaplot-iosx64/0.9.1/koalaplot-iosx64-0.9.1.module",
        "group": "dev.zwander",
        "module": "koalaplot-iosx64",
        "version": "0.9.1"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koalaplot-iosx64/0.9.1/koalaplot-iosx64-0.9.1.module",
        "group": "dev.zwander",
        "module": "koalaplot-iosx64",
        "version": "0.9.1"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../koalaplot-js/0.9.1/koalaplot-js-0.9.1.module",
        "group": "dev.zwander",
        "module": "koalaplot-js",
        "version": "0.9.1"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../koalaplot-js/0.9.1/koalaplot-js-0.9.1.module",
        "group": "dev.zwander",
        "module": "koalaplot-js",
        "version": "0.9.1"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../koalaplot-js/0.9.1/koalaplot-js-0.9.1.module",
        "group": "dev.zwander",
        "module": "koalaplot-js",
        "version": "0.9.1"
      }
    },
    {
      "name": "jsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../koalaplot-js/0.9.1/koalaplot-js-0.9.1.module",
        "group": "dev.zwander",
        "module": "koalaplot-js",
        "version": "0.9.1"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../koalaplot-wasm-js/0.9.1/koalaplot-wasm-js-0.9.1.module",
        "group": "dev.zwander",
        "module": "koalaplot-wasm-js",
        "version": "0.9.1"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../koalaplot-wasm-js/0.9.1/koalaplot-wasm-js-0.9.1.module",
        "group": "dev.zwander",
        "module": "koalaplot-wasm-js",
        "version": "0.9.1"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../koalaplot-wasm-js/0.9.1/koalaplot-wasm-js-0.9.1.module",
        "group": "dev.zwander",
        "module": "koalaplot-wasm-js",
        "version": "0.9.1"
      }
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../koalaplot-wasm-js/0.9.1/koalaplot-wasm-js-0.9.1.module",
        "group": "dev.zwander",
        "module": "koalaplot-wasm-js",
        "version": "0.9.1"
      }
    }
  ]
}
