{
  "formatVersion": "1.1",
  "component": {
    "url": "../../koalaplot/0.9.0/koalaplot-0.9.0.module",
    "group": "dev.zwander",
    "module": "koalaplot",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.8.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "koalaplot-core-js-0.9.0-dev.klib",
          "url": "koalaplot-js-0.9.0.klib",
          "size": 4052774,
          "sha512": "7c8435916cbf570f9797277207b5d17f6ed6706703e59aa7ad0edbf3ec169c620a5ddeffe2e783e27e02581ee6ca6657212a285d9a4a14692c0ec6286a5a484d",
          "sha256": "c9d94303f434703f0adddeea4e828200e19d9781bc2968cd894bfb45887d8dd8",
          "sha1": "e2b4bd9a923f6672e551a71ddcc0d2c71a3caf4d",
          "md5": "06711b8576278a67979dacb3001281a5"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.8.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.8.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "koalaplot-core-js-0.9.0-dev.klib",
          "url": "koalaplot-js-0.9.0.klib",
          "size": 4052774,
          "sha512": "7c8435916cbf570f9797277207b5d17f6ed6706703e59aa7ad0edbf3ec169c620a5ddeffe2e783e27e02581ee6ca6657212a285d9a4a14692c0ec6286a5a484d",
          "sha256": "c9d94303f434703f0adddeea4e828200e19d9781bc2968cd894bfb45887d8dd8",
          "sha1": "e2b4bd9a923f6672e551a71ddcc0d2c71a3caf4d",
          "md5": "06711b8576278a67979dacb3001281a5"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "koalaplot-core-js-0.9.0-dev-sources.jar",
          "url": "koalaplot-js-0.9.0-sources.jar",
          "size": 105907,
          "sha512": "317592c67cc879b42587e61cfac2d87c828f2160181de417658ed16e05114815c73260b26ecaf2828be9ac72802e5ef707042be48dcac49f419a98bc85f4d8fd",
          "sha256": "0be765927e8cd60b0d5978542c568480be0d2b9962641b3f7639b8845c3aa3b7",
          "sha1": "7940cacb1a968f4fe80a480571b842b941f19afb",
          "md5": "2b240e95e159370691ad372bc4ee14f0"
        }
      ]
    },
    {
      "name": "jsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.8.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.8.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "koalaplot-core-0.9.0-dev.kotlin_resources.zip",
          "url": "koalaplot-js-0.9.0-kotlin_resources.kotlin_resources.zip",
          "size": 360,
          "sha512": "0adee3ef1c27a69d426c93f93ee4ed2df270bc95d9e8edaf52536f45c1a105c1dee485e6f4a8d531cdc71b1cd97821ae0fea7d37a611e64b78281f05cc695bf2",
          "sha256": "61011efc0a0f897039725cd0468ef9291b0edbbcef5123e85a4c050cc61d5cc1",
          "sha1": "6b3b61e9470633df95094f3c16386db6cfb41bae",
          "md5": "72980902244f5316d571260b11d52d3a"
        }
      ]
    }
  ]
}
